FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY requirements/base.txt requirements/local.txt ./

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r base.txt -r local.txt

COPY . .

EXPOSE 8081

CMD ["python", "main.py"]
